# Adapted from Andrii Alexieiev’s resume site.
name: Build and publish HTML
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Build and publish HTML
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - name: Install modules
      run: |
        pip3 install jinja2 markdown requests

    - name: Build HTML
      id: build
      env:
        orcid_access_token: ${{ secrets.orcid_access_token }}
      run: |
        generator/generator.py --template-file=generator/template.html --output-file=index.html --orcid-access-token="$ORCID_ACCESS_TOKEN"
        echo ::set-output name=commit::$(git rev-parse HEAD)

    - name: Prepare to commit
      run: |
        git fetch

    - name: Commit and push
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: index.html
        message: Publish revision ${{ steps.build.outputs.commit }}

